# Use postgres with docker
# for start with docker:
# docker run --name currency-postgres -e POSTGRES_PASSWORD=password -p 127.0.0.1:5432:5432 -d postgres
# PostgreSQL configuration example

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: password

development:
  <<: *default
  database: exchange_rates_development

test:
  <<: *default
  database: exchange_rates_test

# Warning. Not use this config for true production. username and password should are secrets.
# this is only demo
production:
  <<: *default
  database: exchange_rates_production
